### ISSUE TITLE
USER STORY: Cancel appointment

### ISSUE THREAD

**Issue by Luinen** [Luinen/practiceJQuery#2]
As a **user**, I can **cancel the reservation**, so that **I can cancel the appointment**.

**Acceptance Criteria**: 

- There should be a cancel button
- When I click on the cancel button...

**Tasks**:

- [ ]  Create the button in HTML
- [ ] Design the button
- [ ]  Create the click event...

**Comment by Luinen** [comment]
This is completed.
